import { Provider } from "jotai";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CarGear",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-cargear.jpg", // icon mặc định (favicon)
    shortcut: "/logo-cargear.jpg", // shortcut icon
    apple: "/logo-cargear.jpg", // icon dành cho thiết bị Apple
  },
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
