import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {fetchFooterData, fetchHeaderData} from "@/lib/api";
import Header from "@/components/header/Header";
import {Footer} from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CarGear",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const headerData = await fetchHeaderData() || null;
    const footerData = await fetchFooterData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header data={headerData} />
      <main>{children}</main>
      <Footer/>
      </body>
    </html>
  );
}
