import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {fetchFooterData, fetchHeaderData} from "@/lib/api";
import Header from "@/components/header/Header";
import {Footer} from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CarGear",
  description: "Generated by create next app",
    icons: {
        icon: "/logo.png",      // icon mặc định (favicon)
        shortcut: "/logo.png",  // shortcut icon
        apple: "/apple-touch-icon.png", // icon dành cho thiết bị Apple
    }
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <main>{children}</main>
      </body>
    </html>
  );
}
